# Default values for osrm.

# Chart name override. Defaults to chart name, i.e. "osrm".
nameOverride: ""
# App name override. Defaults to name built upon release name and chart name.
fullnameOverride: ""

# How many replicas of the statefulset to deploy.
replicaCount: 1

image:
  repository: osrm/osrm-backend
  tag: v5.22.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

# Init containers to add to the pod in statefulset.
# This field is plain yaml that is inserted as-is.
initContainers: []

# Init containers to add to the pod in statefulset.
# This field is a template string that is passed to tpl func before insertion.
initContainersTpl: ""

# Extra arguments to pass to the osrm binary.
extraArgs: []

# Extra volumes to add to the pod.
# This field is plain yaml that is inserted as-is.
extraVolumes: []
#  # Example:
#  - name: something
#    configMap:
#      name: some-volume

# Extra volumes to add to the pod.
# This field is a template string that is passed to tpl func before insertion.
extraVolumesTpl: ""
#  # Example:
#  - name: scripts
#    configMap:
#      name: {{ include "osrm.fullname" . }}-scripts

# Files that are stored in configmap and can be accessed from containers/initContainers.
# This field is a map, where keys are configmap key names and values are file paths relative to chart root.
# File contents is passed to tpl func before insertion.
configTemplatedFiles: {}
#  # Example:
#  download.sh: "files/download.sh.tpl"
#  extract.sh: "files/extract.sh.tpl"

# Kubernetes Service object configuration.
service:
  type: ClusterIP
  port: 80

# Kubernetes Ingress object configuration.
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # requests:
  #   cpu: 200m
  #   memory: 256Mi
  # limits:
  #   cpu: 1000m
  #   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe: null
#  httpGet:
#    path: /route/v1/driving/13.388860,52.517037;13.385983,52.496891
#    port: http

readinessProbe: null
#  httpGet:
#    path: /route/v1/driving/13.388860,52.517037;13.385983,52.496891
#    port: http

# Persistence allows you to store downloaded maps in the persistent store.
# Enable & configure this if you don't want to download the same maps each
# time you deploy.
persistence:
  enabled: false

  # If defined, storageClassName: <storageClass>.
  # If set to "-", storageClassName: "", which disables dynamic provisioning.
  # If set to null (the default), no storageClassName spec is set, choosing
  # 'standard' storage class available with the default provisioner
  # (gcd-pd on GKE, hostpath on minikube, etc).
  # More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: null

  accessModes:
    - ReadWriteOnce
  size: 1Gi

# map configuration enables out-of-the-box map downloading from various sources and required preparations
# (extraction, etc.).
#
# If you do not want to use default downloading mechanics of this chart, you can disable this.
map:
  # Whether the map downloading feature is enabled.
  # If you want to manage maps yourself (e.g. mount pre-existing PV with maps to the pod),
  # set this to false.
  enabled: true

  # Configures what source provider to use to download map.
  # Supported providers:
  # - http
  source: http

  # http section is used when chart is configured to download maps from an HTTP endpoint.
  http:
    # HTTP(S) uri to download map.
    #
    # Some sources/mirrors you may use:
    # - http://download.geofabrik.de
    # - https://download.openstreetmap.fr/extracts/
    uri: https://download.openstreetmap.fr/extracts/europe/monaco.osm.pbf

    # Set to "true" when the .md5 file is available for checksum.
    checkMD5: false

    # http mode files for config map.
    # See top-level 'configTemplatedFiles' for documentation.
    configTemplatedFiles:
      download.sh: "files/http-download.sh.tpl"
      extract.sh: "files/http-extract.sh.tpl"

    # http mode init containers.
    # See tol-level 'initContainersTpl' for documentation.
    initContainersTpl: |-
      - name: map-downloader
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - /scripts/download.sh
        volumeMounts:
          - name: config-files
            mountPath: /scripts
          - name: maps
            mountPath: /data/maps
      - name: map-extractor
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /bin/bash
          - /scripts/extract.sh
        volumeMounts:
          - name: config-files
            mountPath: /scripts
          - name: maps
            mountPath: /data/maps
