apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osrm.fullname" . }}-scripts
  labels: {{ include "osrm.labels" . | nindent 4 }}
data:
  download.sh: |-
    #!/bin/sh
    set -euo pipefail

    cd /data/maps

    if [ ! -r downloaded.txt ]; then
      wget {{ .Values.map.source }}
      touch downloaded.txt
    fi

    {{- if .Values.map.md5 }}
    if [ ! -r checksum.txt ]; then
      wget {{ .Values.map.source }}.md5
      md5sum -c {{ include "osrm.map-filename-pbf" . }}.md5
      touch checksum.txt
    fi
    {{- end }}

    echo "Done!"
    exit 0

  extract.sh: |-
    #!/bin/bash
    set -euo pipefail

    cd /data/maps

    if [ ! -r extracted.txt ]; then
      fname_pbf="{{ include "osrm.map-filename-pbf" . }}"
      fname_osrm="{{ include "osrm.map-filename-osrm" . }}"

      osrm-extract -p /opt/car.lua $fname_pbf
      osrm-partition $fname_osrm
      osrm-customize $fname_osrm

      touch extracted.txt
    fi

    echo "Done!"
    exit 0
